/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chimebox_physical_GPIOChipInfoProvider */

#ifndef _Included_chimebox_physical_GPIOChipInfoProvider
#define _Included_chimebox_physical_GPIOChipInfoProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chimebox_physical_GPIOChipInfoProvider
 * Method:    getGPIOChipInfoInternal
 * Signature: (Ljava/lang/String;)Lchimebox/physical/GPIOChipInfoProvider/GPIOChipInfo;
 */
JNIEXPORT jobject JNICALL Java_chimebox_physical_GPIOChipInfoProvider_getGPIOChipInfoInternal
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
